#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
#  This file is part of fpi
#
#  Copyright 2017 Ikey Doherty <ikey@solus-project.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#

from libfpi.dpkg import control

if __name__ == "__main__":
    print("!!! TESTING !!!")
    control = control.Control()
    # Test google Chrome
    control.parse("tdata/control")

    print("Name: {}".format(control.get_name()))
    print("Summary: {}".format(control.get_summary()))
    print("Description: {}".format(control.get_description()))
